# "docker-compose up -d --build server"
version: "3.8"

services:
  server:
    # image: "nginx:stable-alpine"
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "8000:80"

    # Bind mounts
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile

    # Bind mount for source code
    # Delegated is a slower synch time from src here to container; performance optimization due to reducing frequent writes to container
    # Use cached: when the host performs changes, the container is in read only mode.
    # Use delegated: when docker container performs changes, host is in read only mode.
    # Use default: When both container and host actively and continuously perform changes on data.
    volumes:
      - ./src:/var/www/html:delegated

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  # Utility container
  # Composer is the PHP package/dependency manager
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    # Expose source code directory; bind mount
    volumes:
      - ./src:/var/www/html

  # Utility container to run certain laravel commands, e.g. populate db
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
